# Generated by Selenium IDE
from src.businesslogic.booking import Booking

import pytest


class TestDynochromBooking():
    def setup_method(self, method=None):
        print("Setup method")

        self.booking = Booking()
        self.booking.initBrowser()
        self.vars = {}

    def teardown_method(self, method):
        print("Teardown method")
        self.booking.endBooking()

    def test_dynochromBooking(self):
        self.booking.openPage()

        self.booking.startBooking()
        assert self.booking.successful
